name: Locust Performance Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Locust in headless mode
      run: |
        locust -f locustfile.py --headless -u 20 -r 5 -t 1m --host https://fakestoreapi.com --csv=reports/results

    - name: Upload Locust CSV Results
      uses: actions/upload-artifact@v4
      with:
        name: locust-results
        path: reports/
